name: NET 8

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:

  build-deploy:
      runs-on: ubuntu-latest
      steps:
        - name: checkoutRepo
          uses: actions/checkout@v2  
        - name: Build and Deploy
          uses: ./.github/actions/sam-build-and-deploy
          with:
            aws-access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            #aws-region: ${{ secrets.AWS_REGION }}
            aws-region: 'us-east-2'
            dotnet-version: '8.x'
            template-file-path: ./src/net8/template.yaml
            stack-name: net-8-base
            s3-bucket-name: aws-dotnet-lambda-testing
